import test from 'node:test'; import assert from 'node:assert/strict';
import { createMapping, createMappingVersion, transitionMapping } from '../src/template-studio/mapping-service';

test('creates draft mapping', () => { const item = createMapping({ code: 'PATIENT_V1', moduleCode: 'reception', contractCode: 'PATIENT', mappings: [], createdBy: 'u1' }); assert.equal(item.status, 'DRAFT'); assert.equal(item.version, 1); });
test('rejects unsafe mapping code', () => { assert.throws(() => createMapping({ code: 'bad-code', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }), /Invalid mapping code/); });
test('publishes draft mapping', () => { const item = createMapping({ code: 'A_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }); assert.equal(transitionMapping(item, 'publish').status, 'PUBLISHED'); });
test('creates next version after publish', () => { const item = createMapping({ code: 'A_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }); const published = transitionMapping(item, 'publish'); assert.equal(createMappingVersion(published, [], 'u2').version, 2); });
test('rejects retiring draft', () => { const item = createMapping({ code: 'A_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }); assert.throws(() => transitionMapping(item, 'retire'), /Only PUBLISHED/); });
test('rejects publishing published mapping', () => { const item = transitionMapping(createMapping({ code: 'B_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }), 'publish'); assert.throws(() => transitionMapping(item, 'publish'), /Only DRAFT/); });
test('rejects creating version from draft', () => { const item = createMapping({ code: 'C_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }); assert.throws(() => createMappingVersion(item, [], 'u2'), /existing draft/); });
test('retires published mapping', () => { const item = transitionMapping(createMapping({ code: 'D_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }), 'publish'); assert.equal(transitionMapping(item, 'retire').status, 'RETIRED'); });
test('rejects retiring retired mapping', () => { const item = transitionMapping(transitionMapping(createMapping({ code: 'E_V1', moduleCode: 'x', contractCode: 'y', mappings: [], createdBy: 'u1' }), 'publish'), 'retire'); assert.throws(() => transitionMapping(item, 'retire'), /Only PUBLISHED/); });
test('version preserves contract identity', () => { const item = transitionMapping(createMapping({ code: 'F_V1', moduleCode: 'reception', contractCode: 'PATIENT', mappings: [], createdBy: 'u1' }), 'publish'); const next = createMappingVersion(item, [], 'u2'); assert.equal(next.moduleCode, 'reception'); assert.equal(next.contractCode, 'PATIENT'); });
