import test from 'node:test';
import assert from 'node:assert/strict';
import { SignatureService } from '../src/document-signature/signature.service';

const validSession = { documentId: 'encounter-1', documentVersion: 1, documentSha256: 'a'.repeat(64), sourceArtifactKey: 'documents/1.pdf', expiresAt: new Date(Date.now() + 60_000), createdBy: 'doctor-1' };
const validRect = { pageIndex: 0, x1Pt: 10, y1Pt: 20, x2Pt: 150, y2Pt: 80, pageWidthPt: 595, pageHeightPt: 842, pageRotation: 0 as const };

test('rejects invalid document hash and version before repository call', async () => { const service = new SignatureService(); await assert.rejects(() => service.createSession({ ...validSession, documentSha256: 'bad' }), (error: any) => error.code === 'INVALID_DOCUMENT_HASH'); await assert.rejects(() => service.createSession({ ...validSession, documentVersion: 0 }), (error: any) => error.code === 'INVALID_DOCUMENT_VERSION'); });
test('enforces mutually exclusive freestyle and placeholder placement', async () => { const service = new SignatureService(); await assert.rejects(() => service.createRequest({ ...validRect, sessionId: 's', placementType: 'PLACEHOLDER', signerUserId: 'u', signerRole: 'DOCTOR', idempotencyKey: '1' }), (error: any) => error.code === 'PLACEHOLDER_REQUIRED'); await assert.rejects(() => service.createRequest({ ...validRect, placeholderId: 3, sessionId: 's', placementType: 'FREESTYLE', signerUserId: 'u', signerRole: 'DOCTOR', idempotencyKey: '2' }), (error: any) => error.code === 'PLACEHOLDER_NOT_ALLOWED'); });
test('rejects invalid or out-of-page signature rectangles', async () => { const service = new SignatureService(); await assert.rejects(() => service.createRequest({ ...validRect, x2Pt: 5, sessionId: 's', placementType: 'FREESTYLE', signerUserId: 'u', signerRole: 'DOCTOR', idempotencyKey: '3' }), (error: any) => error.code === 'INVALID_SIGNATURE_RECT'); await assert.rejects(() => service.createRequest({ ...validRect, x2Pt: 700, sessionId: 's', placementType: 'FREESTYLE', signerUserId: 'u', signerRole: 'DOCTOR', idempotencyKey: '4' }), (error: any) => error.code === 'INVALID_SIGNATURE_RECT'); });
test('valid request reaches repository after domain validation', async () => { const service = new SignatureService(); let received: any; (service as any).repository = { createRequest: async (input: any) => { received = input; return { id: 'r1' }; } }; const result = await service.createRequest({ ...validRect, sessionId: 's', placementType: 'FREESTYLE', signerUserId: 'u', signerRole: 'DOCTOR', idempotencyKey: '5' }); assert.deepEqual(result, { id: 'r1' }); assert.equal(received.pageIndex, 0); });
test('complete requires authorized state, assigned signer and matching transaction', async () => { const service = new SignatureService(); let args: any; const request: any = { document_id: 'd1', session_id: 's1', document_sha256: 'a'.repeat(64), signer_user_id: 'doctor-1', status: 'AUTHORIZED', provider_transaction_id: 'provider-tx-1' }; (service as any).repository = { getRequest: async () => request, updateRequestStatus: async (...values: any[]) => { args = values; return { status: 'SIGNED' }; }, audit: async () => undefined }; const hash = 'b'.repeat(64); const result = await service.complete('r1', 'provider-tx-1', 'documents/signed.pdf', hash, 'doctor-1'); assert.equal(result.status, 'SIGNED'); assert.deepEqual(args, ['r1', ['AUTHORIZED'], 'SIGNED', 'provider-tx-1', 'documents/signed.pdf', hash]); await assert.rejects(() => service.complete('r1', 'other-tx', 'documents/signed.pdf', hash, 'doctor-1'), (error: any) => error.code === 'SIGNING_TRANSACTION_MISMATCH'); request.status = 'PREPARED'; await assert.rejects(() => service.complete('r1', 'provider-tx-1', 'documents/signed.pdf', hash, 'doctor-1'), (error: any) => error.code === 'SIGNATURE_NOT_AUTHORIZED'); });
test('cancel records actor audit', async () => { const service = new SignatureService(); let audited: any; (service as any).repository = { getRequest: async () => ({ document_id: 'd1', session_id: 's1', document_sha256: 'a'.repeat(64), status: 'PREPARED' }), updateRequestStatus: async () => ({ status: 'CANCELLED' }), audit: async (value: any) => { audited = value; } }; const result = await service.cancel('r1', 'doctor-1'); assert.equal(result.status, 'CANCELLED'); assert.equal(audited.actorId, 'doctor-1'); assert.equal(audited.action, 'SIGNATURE_CANCELLED'); });
test('session cancellation cancels open requests and locks session', async () => { const service = new SignatureService(); let audits = 0; (service as any).repository = { getSession: async () => ({ id: 's1', status: 'OPEN', document_id: 'd1', document_sha256: 'a'.repeat(64) }), cancelOpenRequests: async () => [{ id: 'r1' }], audit: async () => { audits++; }, setSessionStatus: async () => ({ status: 'CANCELLED' }) }; const result = await service.cancelSession('s1', 'doctor-1'); assert.equal(result.status, 'CANCELLED'); assert.equal(audits, 1); });
test('prepare binds backend document hash, assigned signer and 15 minute TTL', async () => { const service = new SignatureService(); let transition: any; (service as any).repository = { getRequest: async () => ({ signer_user_id: 'doctor-1', document_id: 'doc-1', document_sha256: 'ab'.repeat(32), session_expires_at: new Date(Date.now() + 60 * 60_000) }), updateRequestStatus: async (...args: any[]) => { transition = args; } }; const result = await service.prepare('r1', 'doctor-1'); assert.equal(result.hashBase64, Buffer.from('ab'.repeat(32), 'hex').toString('base64')); assert.equal(result.hashAlgorithm, 'SHA256'); assert.ok(new Date(result.expiresAt).getTime() <= Date.now() + 15 * 60_000); assert.deepEqual(transition.slice(0, 3), ['r1', ['PENDING'], 'PREPARED']); await assert.rejects(() => service.prepare('r1', 'other-user'), (error: any) => error.code === 'SIGNER_MISMATCH'); });
test('agent submission rejects transaction mismatch before cryptographic verification', async () => { const service = new SignatureService(); let audited: any; (service as any).repository = { getRequest: async () => ({ signer_user_id: 'doctor-1', status: 'PREPARED', provider_transaction_id: 'tx-expected', session_expires_at: new Date(Date.now() + 60_000), document_id: 'doc-1', session_id: 's1', document_sha256: 'a'.repeat(64) }), audit: async (value: any) => { audited = value; } }; await assert.rejects(() => service.authorizeAgentSignature('r1', { transactionId: 'tx-other' } as any, 'doctor-1'), (error: any) => error.code === 'SIGNING_TRANSACTION_MISMATCH'); assert.equal(audited.result, 'FAILED'); });
