import test from 'node:test'; import assert from 'node:assert/strict'; import { exportTestCases, importTestCases } from '../src/template-studio/test-case-transfer';
import { generateTestCases } from '../src/template-studio/test-case-generator';
const sample = [{ name: 'Normal', testType: 'NORMAL', inputData: { name: 'A' }, isRequired: true }];
test('exports valid JSON', () => { assert.match(exportTestCases(sample), /Normal/); });
test('round trips test cases', () => { assert.deepEqual(importTestCases(exportTestCases(sample)), sample); });
test('rejects malformed JSON', () => { assert.throws(() => importTestCases('{'), /Invalid/); });
test('rejects non-array payload', () => { assert.throws(() => importTestCases('{}'), /array/); });
test('rejects missing name', () => { assert.throws(() => importTestCases(JSON.stringify([{ testType: 'NORMAL', inputData: {} }])), /name/); });
test('rejects unsupported type', () => { assert.throws(() => importTestCases(JSON.stringify([{ name: 'x', testType: 'BAD', inputData: {} }])), /unsupported/); });
test('rejects array inputData', () => { assert.throws(() => importTestCases(JSON.stringify([{ name: 'x', testType: 'NORMAL', inputData: [] }])), /object/); });
test('trims imported names', () => { assert.equal(importTestCases(JSON.stringify([{ name: ' x ', testType: 'CUSTOM', inputData: {} }]))[0].name, 'x'); });
test('normalizes required flag', () => { assert.equal(importTestCases(JSON.stringify([{ name: 'x', testType: 'CUSTOM', inputData: {}, isRequired: 1 }]))[0].isRequired, true); });
test('export removes extra properties', () => { const output = JSON.parse(exportTestCases([{ ...sample[0], extra: 'x' } as any])); assert.equal(output[0].extra, undefined); });
const generated = generateTestCases({ type: 'object', properties: { name: { type: 'string' }, rows: { type: 'array', items: { type: 'string' } } } }).map(item => ({ ...item, inputData: item.inputData as Record<string, unknown> }));
test('generated normal round trips', () => { assert.deepEqual(importTestCases(exportTestCases([generated[0]]))[0].inputData, generated[0].inputData); });
test('generated empty round trips', () => { assert.deepEqual(importTestCases(exportTestCases([generated[1]]))[0].inputData, generated[1].inputData); });
test('generated long round trips', () => { assert.equal((importTestCases(exportTestCases([generated[2]]))[0].inputData as any).name.length, 500); });
test('generated boundary round trips', () => { assert.deepEqual(importTestCases(exportTestCases([generated[3]]))[0].inputData, generated[3].inputData); });
test('generated many rows round trips', () => { assert.equal(((importTestCases(exportTestCases([generated[4]]))[0].inputData as any).rows).length, 2); });
test('multiple generated cases preserve order', () => { assert.deepEqual(importTestCases(exportTestCases(generated)).map(x => x.testType), generated.map(x => x.testType)); });
test('multiple generated cases preserve required flags', () => { assert.deepEqual(importTestCases(exportTestCases(generated)).map(x => x.isRequired), generated.map(x => x.isRequired)); });
test('unicode generated names are safe', () => { const item = { ...generated[0], name: 'Bệnh án' }; assert.equal(importTestCases(exportTestCases([item]))[0].name, 'Bệnh án'); });
test('empty generated collection exports', () => { assert.deepEqual(importTestCases(exportTestCases([])), []); });
test('import export is deterministic', () => { assert.equal(exportTestCases(importTestCases(exportTestCases(generated))), exportTestCases(generated)); });
