FROM carbone/carbone-ee:full-5.9.0
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends wget fonts-noto-core fonts-noto-cjk fonts-liberation2 \
    && rm -rf /var/lib/apt/lists/*
USER carbone
