import React, { createContext, useContext } from 'react';
import { CatalogItem } from '../../../services/catalogService';

export interface DynamicFormContextType {
    formType: string;
    initialData: any;
    isChild: boolean;
    isStudent: boolean;
    activeTab: 'admin' | 'history' | 'exam' | 'lab' | 'conclusion';
    setActiveTab: React.Dispatch<React.SetStateAction<'admin' | 'history' | 'exam' | 'lab' | 'conclusion'>>;

    // State for HIS Sync
    hisSearchQuery: string;
    setHisSearchQuery: React.Dispatch<React.SetStateAction<string>>;
    isFetchingHis: boolean;
    setIsFetchingHis: React.Dispatch<React.SetStateAction<boolean>>;
    hisSyncMessage: { type: 'success' | 'error', text: string } | null;
    setHisSyncMessage: React.Dispatch<React.SetStateAction<{ type: 'success' | 'error', text: string } | null>>;
    hisSource: 'HEALTH_CHECK_MASTER' | 'HIS_DIRECT' | null;
    setHisSource: React.Dispatch<React.SetStateAction<'HEALTH_CHECK_MASTER' | 'HIS_DIRECT' | null>>;
    handleFetchHisData: () => Promise<void>;

    // State for Specialty Exam tabs
    specialtyMetadata: Record<string, { doctorId: string, status: string, updatedAt: string }>;
    setSpecialtyMetadata: React.Dispatch<React.SetStateAction<Record<string, { doctorId: string, status: string, updatedAt: string }>>>;
    doctors: CatalogItem[];
    setDoctors: React.Dispatch<React.SetStateAction<CatalogItem[]>>;

    // 1. Administrative & Lookup State
    patientId: string;
    setPatientId: React.Dispatch<React.SetStateAction<string>>;
    patientName: string;
    setPatientName: React.Dispatch<React.SetStateAction<string>>;
    cccd: string;
    setCccd: React.Dispatch<React.SetStateAction<string>>;
    dob: string;
    setDob: React.Dispatch<React.SetStateAction<string>>;
    gender: string;
    setGender: React.Dispatch<React.SetStateAction<string>>;
    docNo: string;
    setDocNo: React.Dispatch<React.SetStateAction<string>>;
    address: string;
    setAddress: React.Dispatch<React.SetStateAction<string>>;
    phone: string;
    setPhone: React.Dispatch<React.SetStateAction<string>>;
    ethnic: string;
    setEthnic: React.Dispatch<React.SetStateAction<string>>;
    cccdDate: string;
    setCccdDate: React.Dispatch<React.SetStateAction<string>>;
    cccdPlace: string;
    setCccdPlace: React.Dispatch<React.SetStateAction<string>>;
    bloodGroup: string;
    setBloodGroup: React.Dispatch<React.SetStateAction<string>>;
    targetGroup: string;
    setTargetGroup: React.Dispatch<React.SetStateAction<string>>;
    fundingSource: string;
    setFundingSource: React.Dispatch<React.SetStateAction<string>>;
    maGtinCskcb: string;
    setMaGtinCskcb: React.Dispatch<React.SetStateAction<string>>;
    maTinhCuTru: string;
    setMaTinhCuTru: React.Dispatch<React.SetStateAction<string>>;
    maXaCuTru: string;
    setMaXaCuTru: React.Dispatch<React.SetStateAction<string>>;
    lyDoVv: string;
    setLyDoVv: React.Dispatch<React.SetStateAction<string>>;
    loaiHinhKcb: string;
    setLoaiHinhKcb: React.Dispatch<React.SetStateAction<string>>;
    ngayVao: string;
    setNgayVao: React.Dispatch<React.SetStateAction<string>>;
    maCskcb: string;
    setMaCskcb: React.Dispatch<React.SetStateAction<string>>;
    quocTich: string;
    setQuocTich: React.Dispatch<React.SetStateAction<string>>;
    conThuMay: string;
    setConThuMay: React.Dispatch<React.SetStateAction<string>>;
    tongSoCon: string;
    setTongSoCon: React.Dispatch<React.SetStateAction<string>>;
    maTinhCuTruNghMe: string;
    setMaTinhCuTruNghMe: React.Dispatch<React.SetStateAction<string>>;
    maXaCuTruNghMe: string;
    setMaXaCuTruNghMe: React.Dispatch<React.SetStateAction<string>>;
    chucDanhTrenTau: string;
    setChucDanhTrenTau: React.Dispatch<React.SetStateAction<string>>;
    tenChuTau: string;
    setTenChuTau: React.Dispatch<React.SetStateAction<string>>;
    diaChiChuTau: string;
    setDiaChiChuTau: React.Dispatch<React.SetStateAction<string>>;
    khuVucHoatDongTau: string;
    setKhuVucHoatDongTau: React.Dispatch<React.SetStateAction<string>>;

    provinces: CatalogItem[];
    ethnicities: CatalogItem[];
    occupations: CatalogItem[];
    nations: CatalogItem[];
    wards: CatalogItem[];
    setWards: React.Dispatch<React.SetStateAction<CatalogItem[]>>;
    wardsNghMe: CatalogItem[];
    workplaces: CatalogItem[];
    setWorkplaces: React.Dispatch<React.SetStateAction<CatalogItem[]>>;

    guardianName: string;
    setGuardianName: React.Dispatch<React.SetStateAction<string>>;
    guardianCccd: string;
    setGuardianCccd: React.Dispatch<React.SetStateAction<string>>;
    escortName: string;
    setEscortName: React.Dispatch<React.SetStateAction<string>>;
    escortCccd: string;
    setEscortCccd: React.Dispatch<React.SetStateAction<string>>;
    escortRelation: string;
    setEscortRelation: React.Dispatch<React.SetStateAction<string>>;
    licenseClass: string;
    setLicenseClass: React.Dispatch<React.SetStateAction<string>>;
    driverExamPurpose: string;
    setDriverExamPurpose: React.Dispatch<React.SetStateAction<string>>;
    chucDanh: string;
    setChucDanh: React.Dispatch<React.SetStateAction<string>>;
    noiCongTac: string;
    setNoiCongTac: React.Dispatch<React.SetStateAction<string>>;
    viTriLamViec: string;
    setViTriLamViec: React.Dispatch<React.SetStateAction<string>>;
    boPhanLamViec: string;
    setBoPhanLamViec: React.Dispatch<React.SetStateAction<string>>;
    offshoreExp: string;
    setOffshoreExp: React.Dispatch<React.SetStateAction<string>>;
    railwayFit: string;
    setRailwayFit: React.Dispatch<React.SetStateAction<string>>;

    maNgheNghiep: string;
    setMaNgheNghiep: React.Dispatch<React.SetStateAction<string>>;
    noiCongTacHienTai: string;
    setNoiCongTacHienTai: React.Dispatch<React.SetStateAction<string>>;
    ngayBatDauLamViecHienTai: string;
    setNgayBatDauLamViecHienTai: React.Dispatch<React.SetStateAction<string>>;
    ngheCongViecTruocDay: string;
    setNgheCongViecTruocDay: React.Dispatch<React.SetStateAction<string>>;
    thoiGianLamViecTruocDayNam: string;
    setThoiGianLamViecTruocDayNam: React.Dispatch<React.SetStateAction<string>>;
    thoiGianLamViecTruocDayThang: string;
    setThoiGianLamViecTruocDayThang: React.Dispatch<React.SetStateAction<string>>;
    tuNgayLamViecTruocDay: string;
    setTuNgayLamViecTruocDay: React.Dispatch<React.SetStateAction<string>>;
    denNgayLamViecTruocDay: string;
    setDenNgayLamViecTruocDay: React.Dispatch<React.SetStateAction<string>>;

    milestones: Record<string, string>;
    setMilestones: React.Dispatch<React.SetStateAction<Record<string, string>>>;

    // 2. Tiền sử bệnh & tiêm chủng
    tsgdMacBenh: string;
    setTsgdMacBenh: React.Dispatch<React.SetStateAction<string>>;
    tsTiepXucLao: string;
    setTsTiepXucLao: React.Dispatch<React.SetStateAction<string>>;
    tsgdMaBenh: string;
    setTsgdMaBenh: React.Dispatch<React.SetStateAction<string>>;
    tsbtMaBenh: string;
    setTsbtMaBenh: React.Dispatch<React.SetStateAction<string>>;
    tsbtNghienRuou: string;
    setTsbtNghienRuou: React.Dispatch<React.SetStateAction<string>>;
    tsbtMaBenhKhac: string;
    setTsbtMaBenhKhac: React.Dispatch<React.SetStateAction<string>>;
    nhiKhoaLamSangKhac: string;
    setNhiKhoaLamSangKhac: React.Dispatch<React.SetStateAction<string>>;
    tsbtNamPhatHienBenh: string;
    setTsbtNamPhatHienBenh: React.Dispatch<React.SetStateAction<string>>;
    tiemChungBcg: string;
    setTiemChungBcg: React.Dispatch<React.SetStateAction<string>>;
    tiemChungBhHgUv: string;
    setTiemChungBhHgUv: React.Dispatch<React.SetStateAction<string>>;
    tiemChungSoi: string;
    setTiemChungSoi: React.Dispatch<React.SetStateAction<string>>;
    tiemChungBaiLiet: string;
    setTiemChungBaiLiet: React.Dispatch<React.SetStateAction<string>>;
    tiemChungVnnbB: string;
    setTiemChungVnnbB: React.Dispatch<React.SetStateAction<string>>;
    tiemChungVgb: string;
    setTiemChungVgb: React.Dispatch<React.SetStateAction<string>>;
    tiemChungCacLoaiKhac: string;
    setTiemChungCacLoaiKhac: React.Dispatch<React.SetStateAction<string>>;
    tiemChungVacXinKhac: string;
    setTiemChungVacXinKhac: React.Dispatch<React.SetStateAction<string>>;

    // Tiền sử thai sản (QĐ 2062)
    tsbtThaiSan: string;
    setTsbtThaiSan: React.Dispatch<React.SetStateAction<string>>;
    tsbtMaBenhThaiSan: string;
    setTsbtMaBenhThaiSan: React.Dispatch<React.SetStateAction<string>>;
    tsbtTenThuocThaiSan: string;
    setTsbtTenThuocThaiSan: React.Dispatch<React.SetStateAction<string>>;

    // Tiền sử sản phụ khoa (nữ)
    coKinhNguyetNamBaoNhieuTuoi: string;
    setCoKinhNguyetNamBaoNhieuTuoi: React.Dispatch<React.SetStateAction<string>>;
    tinhChatKinhNguyet: string;
    setTinhChatKinhNguyet: React.Dispatch<React.SetStateAction<string>>;
    chuKyKinh: string;
    setChuKyKinh: React.Dispatch<React.SetStateAction<string>>;
    luongKinh: string;
    setLuongKinh: React.Dispatch<React.SetStateAction<string>>;
    dauBungKinh: string;
    setDauBungKinh: React.Dispatch<React.SetStateAction<string>>;
    daLapGiaDinh: string;
    setDaLapGiaDinh: React.Dispatch<React.SetStateAction<string>>;
    para: string;
    setPara: React.Dispatch<React.SetStateAction<string>>;
    daTungMoSanPhuKhoaChua: string;
    setDaTungMoSanPhuKhoaChua: React.Dispatch<React.SetStateAction<string>>;
    soLanMoSanPhuKhoa: string;
    setSoLanMoSanPhuKhoa: React.Dispatch<React.SetStateAction<string>>;
    ghiRoMoSanPhuKhoa: string;
    setGhiRoMoSanPhuKhoa: React.Dispatch<React.SetStateAction<string>>;
    dangApDungBpttKhong: string;
    setDangApDungBpttKhong: React.Dispatch<React.SetStateAction<string>>;
    bienPhapTranhThai: string;
    setBienPhapTranhThai: React.Dispatch<React.SetStateAction<string>>;

    // Tiền sử lái xe
    ts5Nam: number;
    setTs5Nam: React.Dispatch<React.SetStateAction<number>>;
    tsThanKinh: number;
    setTsThanKinh: React.Dispatch<React.SetStateAction<number>>;
    tsMat: number;
    setTsMat: React.Dispatch<React.SetStateAction<number>>;
    tsTai: number;
    setTsTai: React.Dispatch<React.SetStateAction<number>>;
    tsTimMach: number;
    setTsTimMach: React.Dispatch<React.SetStateAction<number>>;
    tsPhauThuatTim: number;
    setTsPhauThuatTim: React.Dispatch<React.SetStateAction<number>>;
    tsHuyetAp: number;
    setTsHuyetAp: React.Dispatch<React.SetStateAction<number>>;
    tsKhoTho: number;
    setTsKhoTho: React.Dispatch<React.SetStateAction<number>>;
    tsPhoiHen: number;
    setTsPhoiHen: React.Dispatch<React.SetStateAction<number>>;
    tsThan: number;
    setTsThan: React.Dispatch<React.SetStateAction<number>>;
    tsTieuDuong: number;
    setTsTieuDuong: React.Dispatch<React.SetStateAction<number>>;
    tsTamThan: number;
    setTsTamThan: React.Dispatch<React.SetStateAction<number>>;
    tsYThuc: number;
    setTsYThuc: React.Dispatch<React.SetStateAction<number>>;
    tsChongMat: number;
    setTsChongMat: React.Dispatch<React.SetStateAction<number>>;
    tsTieuHoa: number;
    setTsTieuHoa: React.Dispatch<React.SetStateAction<number>>;
    tsGiacNgu: number;
    setTsGiacNgu: React.Dispatch<React.SetStateAction<number>>;
    tsTaiBien: number;
    setTsTaiBien: React.Dispatch<React.SetStateAction<number>>;
    tsSuDungRuou: number;
    setTsSuDungRuou: React.Dispatch<React.SetStateAction<number>>;
    tsSuDungMaTuy: number;
    setTsSuDungMaTuy: React.Dispatch<React.SetStateAction<number>>;
    tsBenhCotSong: number;
    setTsBenhCotSong: React.Dispatch<React.SetStateAction<number>>;
    tsMacBenh: number;
    setTsMacBenh: React.Dispatch<React.SetStateAction<number>>;
    tsbtMaBenhNgheNghiep: string;
    setTsbtMaBenhNgheNghiep: React.Dispatch<React.SetStateAction<string>>;
    tsbtNamPhatHienBenhNgheNghiep: string;
    setTsbtNamPhatHienBenhNgheNghiep: React.Dispatch<React.SetStateAction<string>>;

    // 3. Physical Measurements
    height: string;
    setHeight: React.Dispatch<React.SetStateAction<string>>;
    weight: string;
    setWeight: React.Dispatch<React.SetStateAction<string>>;
    pulse: string;
    setPulse: React.Dispatch<React.SetStateAction<string>>;
    bp: string;
    setBp: React.Dispatch<React.SetStateAction<string>>;
    vongDau: string;
    setVongDau: React.Dispatch<React.SetStateAction<string>>;
    vongNguc: string;
    setVongNguc: React.Dispatch<React.SetStateAction<string>>;
    sinhNon: string;
    setSinhNon: React.Dispatch<React.SetStateAction<string>>;
    tuanThai: string;
    setTuanThai: React.Dispatch<React.SetStateAction<string>>;
    birthWeight: string;
    setBirthWeight: React.Dispatch<React.SetStateAction<string>>;
    lucBopTayThuan: string;
    setLucBopTayThuan: React.Dispatch<React.SetStateAction<string>>;
    lucBopTayKhongThuan: string;
    setLucBopTayKhongThuan: React.Dispatch<React.SetStateAction<string>>;
    lucKeoLung: string;
    setLucKeoLung: React.Dispatch<React.SetStateAction<string>>;
    bmi: string;

    // 4. Clinical specialty results
    internalExam: string;
    setInternalExam: React.Dispatch<React.SetStateAction<string>>;
    eyeExam: string;
    setEyeExam: React.Dispatch<React.SetStateAction<string>>;
    entExam: string;
    setEntExam: React.Dispatch<React.SetStateAction<string>>;
    dentalExam: string;
    setDentalExam: React.Dispatch<React.SetStateAction<string>>;
    externalExam: string;
    setExternalExam: React.Dispatch<React.SetStateAction<string>>;
    dermatologyExam: string;
    setDermatologyExam: React.Dispatch<React.SetStateAction<string>>;
    gynExam: string;
    setGynExam: React.Dispatch<React.SetStateAction<string>>;

    khongKinhMatPhai: string;
    setKhongKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    khongKinhMatTrai: string;
    setKhongKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    coKinhMatPhai: string;
    setCoKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    coKinhMatTrai: string;
    setCoKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    khongKinhHaiMat: string;
    setKhongKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    coKinhHaiMat: string;
    setCoKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    sacGiac: string;
    setSacGiac: React.Dispatch<React.SetStateAction<string>>;
    thiTruongNgangHaiMat: string;
    setThiTruongNgangHaiMat: React.Dispatch<React.SetStateAction<string>>;
    thiTruongDungHaiMat: string;
    setThiTruongDungHaiMat: React.Dispatch<React.SetStateAction<string>>;

    taiTraiNoiThuong: string;
    setTaiTraiNoiThuong: React.Dispatch<React.SetStateAction<string>>;
    taiTraiNoiTham: string;
    setTaiTraiNoiTham: React.Dispatch<React.SetStateAction<string>>;
    taiPhaiNoiThuong: string;
    setTaiPhaiNoiThuong: React.Dispatch<React.SetStateAction<string>>;
    taiPhaiNoiTham: string;
    setTaiPhaiNoiTham: React.Dispatch<React.SetStateAction<string>>;

    hamTren: string;
    setHamTren: React.Dispatch<React.SetStateAction<string>>;
    hamDuoi: string;
    setHamDuoi: React.Dispatch<React.SetStateAction<string>>;

    khamTheLucPl: string;
    setKhamTheLucPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaTuanHoanPl: string;
    setNoiKhoaTuanHoanPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaHoHapPl: string;
    setNoiKhoaHoHapPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaTieuHoaPl: string;
    setNoiKhoaTieuHoaPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaThanTietnieuPl: string;
    setNoiKhoaThanTietnieuPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaNoiTietPl: string;
    setNoiKhoaNoiTietPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaCoXuongKhopPl: string;
    setNoiKhoaCoXuongKhopPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaThanKinhPl: string;
    setNoiKhoaThanKinhPl: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaTamThanPl: string;
    setNoiKhoaTamThanPl: React.Dispatch<React.SetStateAction<string>>;
    khamNgoaiKhoaPl: string;
    setKhamNgoaiKhoaPl: React.Dispatch<React.SetStateAction<string>>;
    khamDaLieuPl: string;
    setKhamDaLieuPl: React.Dispatch<React.SetStateAction<string>>;
    khamSanPhuKhoaPl: string;
    setKhamSanPhuKhoaPl: React.Dispatch<React.SetStateAction<string>>;
    khamMatPl: string;
    setKhamMatPl: React.Dispatch<React.SetStateAction<string>>;
    khamTaiMuiHongPl: string;
    setKhamTaiMuiHongPl: React.Dispatch<React.SetStateAction<string>>;
    khamRangHamMatPl: string;
    setKhamRangHamMatPl: React.Dispatch<React.SetStateAction<string>>;

    nhiTuanHoan: string;
    setNhiTuanHoan: React.Dispatch<React.SetStateAction<string>>;
    nhiHoHap: string;
    setNhiHoHap: React.Dispatch<React.SetStateAction<string>>;
    nhiTieuHoa: string;
    setNhiTieuHoa: React.Dispatch<React.SetStateAction<string>>;
    nhiTietNieu: string;
    setNhiTietNieu: React.Dispatch<React.SetStateAction<string>>;
    nhiThanKinh: string;
    setNhiThanKinh: React.Dispatch<React.SetStateAction<string>>;
    nhiTamThan: string;
    setNhiTamThan: React.Dispatch<React.SetStateAction<string>>;
    nhiKhac: string;
    setNhiKhac: React.Dispatch<React.SetStateAction<string>>;
    milestoneCheck: string;
    setMilestoneCheck: React.Dispatch<React.SetStateAction<string>>;

    // 5. Paraclinical/Labs
    hemoglobin: string;
    setHemoglobin: React.Dispatch<React.SetStateAction<string>>;
    glycemia: string;
    setGlycemia: React.Dispatch<React.SetStateAction<string>>;
    protein: string;
    setProtein: React.Dispatch<React.SetStateAction<string>>;
    kqXnMaiTuy: string;
    setKqXnMaiTuy: React.Dispatch<React.SetStateAction<string>>;
    kqXnNongDoCon: string;
    setKqXnNongDoCon: React.Dispatch<React.SetStateAction<string>>;
    kqXnKhac: string;
    setKqXnKhac: React.Dispatch<React.SetStateAction<string>>;
    paraclinicalItems: any[];
    setParaclinicalItems: React.Dispatch<React.SetStateAction<any[]>>;
    labSubTab: 'XN' | 'HA' | 'TD';
    setLabSubTab: React.Dispatch<React.SetStateAction<'XN' | 'HA' | 'TD'>>;

    handleHemoglobinChange: (val: string) => void;
    handleGlycemiaChange: (val: string) => void;
    handleProteinChange: (val: string) => void;
    syncGridToCoreFields: (items: any[]) => void;

    // Specialized occupation states
    noiKhoaTamThan: string;
    setNoiKhoaTamThan: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaThanKinh: string;
    setNoiKhoaThanKinh: React.Dispatch<React.SetStateAction<string>>;
    tenThuoc: string;
    setTenThuoc: React.Dispatch<React.SetStateAction<string>>;

    kqTamThan: string;
    setKqTamThan: React.Dispatch<React.SetStateAction<string>>;
    kqThanKinh: string;
    setKqThanKinh: React.Dispatch<React.SetStateAction<string>>;
    kqTimMach: string;
    setKqTimMach: React.Dispatch<React.SetStateAction<string>>;
    kqHoHap: string;
    setKqHoHap: React.Dispatch<React.SetStateAction<string>>;
    kqNoiTiet: string;
    setKqNoiTiet: React.Dispatch<React.SetStateAction<string>>;
    kqNgoaiKhoa: string;
    setKqNgoaiKhoa: React.Dispatch<React.SetStateAction<string>>;
    kqDaLieu: string;
    setKqDaLieu: React.Dispatch<React.SetStateAction<string>>;
    kqTietNieu: string;
    setKqTietNieu: React.Dispatch<React.SetStateAction<string>>;
    kqSinhDuc: string;
    setKqSinhDuc: React.Dispatch<React.SetStateAction<string>>;
    kqTaiMuiHong: string;
    setKqTaiMuiHong: React.Dispatch<React.SetStateAction<string>>;
    kqCoXuongKhop: string;
    setKqCoXuongKhop: React.Dispatch<React.SetStateAction<string>>;
    kqNoiTietChuyenHoa: string;
    setKqNoiTietChuyenHoa: React.Dispatch<React.SetStateAction<string>>;
    duTieuChuanDkPtgtDuongSat: string;
    setDuTieuChuanDkPtgtDuongSat: React.Dispatch<React.SetStateAction<string>>;

    lucKeoThan: string;
    setLucKeoThan: React.Dispatch<React.SetStateAction<string>>;
    haTamThu: string;
    setHaTamThu: React.Dispatch<React.SetStateAction<string>>;
    haTamTruong: string;
    setHaTamTruong: React.Dispatch<React.SetStateAction<string>>;
    nhipTim: string;
    setNhipTim: React.Dispatch<React.SetStateAction<string>>;
    timMach: string;
    setTimMach: React.Dispatch<React.SetStateAction<string>>;
    hoHap: string;
    setHoHap: React.Dispatch<React.SetStateAction<string>>;
    tietNieuSinhDuc: string;
    setTietNieuSinhDuc: React.Dispatch<React.SetStateAction<string>>;
    noiKhoaTieuHoa: string;
    setNoiKhoaTieuHoa: React.Dispatch<React.SetStateAction<string>>;
    ganMat: string;
    setGanMat: React.Dispatch<React.SetStateAction<string>>;
    mauCoQuanTaoMau: string;
    setMauCoQuanTaoMau: React.Dispatch<React.SetStateAction<string>>;
    daToChucDuoiDa: string;
    setDaToChucDuoiDa: React.Dispatch<React.SetStateAction<string>>;
    kqCoXuongKhopM5: string;
    setKqCoXuongKhopM5: React.Dispatch<React.SetStateAction<string>>;
    thanKinhM5: string;
    setThanKinhM5: React.Dispatch<React.SetStateAction<string>>;
    maBenhNgoaiKhoa: string;
    setMaBenhNgoaiKhoa: React.Dispatch<React.SetStateAction<string>>;
    khamTaiMuiHongM5: string;
    setKhamTaiMuiHongM5: React.Dispatch<React.SetStateAction<string>>;
    khamMatM5: string;
    setKhamMatM5: React.Dispatch<React.SetStateAction<string>>;
    benhKhac: string;
    setBenhKhac: React.Dispatch<React.SetStateAction<string>>;
    khamMatThiGiacMau: string;
    setKhamMatThiGiacMau: React.Dispatch<React.SetStateAction<string>>;
    chiSoHc: string;
    setChiSoHc: React.Dispatch<React.SetStateAction<string>>;
    chiSoBachCau: string;
    setChiSoBachCau: React.Dispatch<React.SetStateAction<string>>;
    chiSoTieuCau: string;
    setChiSoTieuCau: React.Dispatch<React.SetStateAction<string>>;
    congThucBc: string;
    setCongThucBc: React.Dispatch<React.SetStateAction<string>>;
    thoiGianHowell: string;
    setThoiGianHowell: React.Dispatch<React.SetStateAction<string>>;
    cholesterol: string;
    setCholesterol: React.Dispatch<React.SetStateAction<string>>;
    triglycerid: string;
    setTriglycerid: React.Dispatch<React.SetStateAction<string>>;
    hdl: string;
    setHdl: React.Dispatch<React.SetStateAction<string>>;
    ldl: string;
    setLdl: React.Dispatch<React.SetStateAction<string>>;
    rpr: string;
    setRpr: React.Dispatch<React.SetStateAction<string>>;
    tpha: string;
    setTpha: React.Dispatch<React.SetStateAction<string>>;
    hbsag: string;
    setHbsag: React.Dispatch<React.SetStateAction<string>>;
    hbeag: string;
    setHbeag: React.Dispatch<React.SetStateAction<string>>;
    hcvab: string;
    setHcvab: React.Dispatch<React.SetStateAction<string>>;
    havab: string;
    setHavab: React.Dispatch<React.SetStateAction<string>>;
    hiv: string;
    setHiv: React.Dispatch<React.SetStateAction<string>>;
    xnKhac: string;
    setXnKhac: React.Dispatch<React.SetStateAction<string>>;
    nongDoConMau: string;
    setNongDoConMau: React.Dispatch<React.SetStateAction<string>>;
    nuocTieuMaTuy: string;
    setNuocTieuMaTuy: React.Dispatch<React.SetStateAction<string>>;
    nuocTieuAmphetamine: string;
    setNuocTieuAmphetamine: React.Dispatch<React.SetStateAction<string>>;
    nuocTieuDuong: string;
    setNuocTieuDuong: React.Dispatch<React.SetStateAction<string>>;
    nuocTieuProtein: string;
    setNuocTieuProtein: React.Dispatch<React.SetStateAction<string>>;
    nuocTieuKhac: string;
    setNuocTieuKhac: React.Dispatch<React.SetStateAction<string>>;
    ketQuaChanDoanHinhAnh: string;
    setKetQuaChanDoanHinhAnh: React.Dispatch<React.SetStateAction<string>>;
    ketQuaDienTim: string;
    setKetQuaDienTim: React.Dispatch<React.SetStateAction<string>>;
    chucNangHoHap: string;
    setChucNangHoHap: React.Dispatch<React.SetStateAction<string>>;
    ketQuaSieuAmBung: string;
    setKetQuaSieuAmBung: React.Dispatch<React.SetStateAction<string>>;
    khaNangChiuSong: string;
    setKhaNangChiuSong: React.Dispatch<React.SetStateAction<string>>;
    hanChe: string;
    setHanChe: React.Dispatch<React.SetStateAction<string>>;
    yeuCauDeoKinh: string;
    setYeuCauDeoKinh: React.Dispatch<React.SetStateAction<string>>;
    vongNgucTrungBinh: string;
    setVongNgucTrungBinh: React.Dispatch<React.SetStateAction<string>>;
    noiTietDinhDuongChuyenHoa: string;
    setNoiTietDinhDuongChuyenHoa: React.Dispatch<React.SetStateAction<string>>;
    roiLoanHanhViTamThan: string;
    setRoiLoanHanhViTamThan: React.Dispatch<React.SetStateAction<string>>;
    xaKhongKinhMatPhai: string;
    setXaKhongKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    xaKhongKinhMatTrai: string;
    setXaKhongKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    xaKhongKinhHaiMat: string;
    setXaKhongKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    xaCoKinhMatPhai: string;
    setXaCoKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    xaCoKinhMatTrai: string;
    setXaCoKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    xaCoKinhHaiMat: string;
    setXaCoKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    ganKhongKinhMatPhai: string;
    setGanKhongKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    ganKhongKinhMatTrai: string;
    setGanKhongKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    ganKhongKinhHaiMat: string;
    setGanKhongKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    ganCoKinhMatPhai: string;
    setGanCoKinhMatPhai: React.Dispatch<React.SetStateAction<string>>;
    ganCoKinhMatTrai: string;
    setGanCoKinhMatTrai: React.Dispatch<React.SetStateAction<string>>;
    ganCoKinhHaiMat: string;
    setGanCoKinhHaiMat: React.Dispatch<React.SetStateAction<string>>;
    khamMatThiTruongPhai: string;
    setKhamMatThiTruongPhai: React.Dispatch<React.SetStateAction<string>>;
    khamMatThiTruongTrai: string;
    setKhamMatThiTruongTrai: React.Dispatch<React.SetStateAction<string>>;
    taiPhai500hz: string;
    setTaiPhai500hz: React.Dispatch<React.SetStateAction<string>>;
    taiTrai500hz: string;
    setTaiTrai500hz: React.Dispatch<React.SetStateAction<string>>;
    taiPhai2000hz: string;
    setTaiPhai2000hz: React.Dispatch<React.SetStateAction<string>>;
    taiTrai2000hz: string;
    setTaiTrai2000hz: React.Dispatch<React.SetStateAction<string>>;
    taiPhai3000hz: string;
    setTaiPhai3000hz: React.Dispatch<React.SetStateAction<string>>;
    taiTrai3000hz: string;
    setTaiTrai3000hz: React.Dispatch<React.SetStateAction<string>>;
    taiPhai4000hz: string;
    setTaiPhai4000hz: React.Dispatch<React.SetStateAction<string>>;
    taiTrai4000hz: string;
    setTaiTrai4000hz: React.Dispatch<React.SetStateAction<string>>;
    taiPhai6000hz: string;
    setTaiPhai6000hz: React.Dispatch<React.SetStateAction<string>>;
    taiTrai6000hz: string;
    setTaiTrai6000hz: React.Dispatch<React.SetStateAction<string>>;
    thanKinhTamLy: string;
    setThanKinhTamLy: React.Dispatch<React.SetStateAction<string>>;

    // Vital signs & evaluation
    nhietDo: string;
    setNhietDo: React.Dispatch<React.SetStateAction<string>>;
    nhipTho: string;
    setNhipTho: React.Dispatch<React.SetStateAction<string>>;
    gioKham: string;
    setGioKham: React.Dispatch<React.SetStateAction<string>>;
    dgDhstNhietDo: string;
    setDgDhstNhietDo: React.Dispatch<React.SetStateAction<string>>;
    dgDhstMach: string;
    setDgDhstMach: React.Dispatch<React.SetStateAction<string>>;
    dgDhstNhipTho: string;
    setDgDhstNhipTho: React.Dispatch<React.SetStateAction<string>>;

    // Child nutrition, development, and immunization
    chieuDaiTuoiSd: string;
    setChieuDaiTuoiSd: React.Dispatch<React.SetStateAction<string>>;
    canNangTuoiSd: string;
    setCanNangTuoiSd: React.Dispatch<React.SetStateAction<string>>;
    dgVongDau: string;
    setDgVongDau: React.Dispatch<React.SetStateAction<string>>;
    chuViVongCanhTay: string;
    setChuViVongCanhTay: React.Dispatch<React.SetStateAction<string>>;
    phuDinhDuong: string;
    setPhuDinhDuong: React.Dispatch<React.SetStateAction<string>>;
    thieuMau: string;
    setThieuMau: React.Dispatch<React.SetStateAction<string>>;
    coiXuong: string;
    setCoiXuong: React.Dispatch<React.SetStateAction<string>>;
    suyDinhDuong: string;
    setSuyDinhDuong: React.Dispatch<React.SetStateAction<string>>;
    thuaCanBeoPhi: string;
    setThuaCanBeoPhi: React.Dispatch<React.SetStateAction<string>>;
    ptTinhThanBinhThuong: string;
    setPtTinhThanBinhThuong: React.Dispatch<React.SetStateAction<string>>;
    ptVanDongBinhThuong: string;
    setPtVanDongBinhThuong: React.Dispatch<React.SetStateAction<string>>;
    nguyCoTuKy: string;
    setNguyCoTuKy: React.Dispatch<React.SetStateAction<string>>;
    tiemChungLao: string;
    setTiemChungLao: React.Dispatch<React.SetStateAction<string>>;
    tiemChungVgbMui1: string;
    setTiemChungVgbMui1: React.Dispatch<React.SetStateAction<string>>;
    tiemChungDayDu: string;
    setTiemChungDayDu: React.Dispatch<React.SetStateAction<string>>;

    // Child clinical exam fields
    lamSangQuanSat: string;
    setLamSangQuanSat: React.Dispatch<React.SetStateAction<string>>;
    mauSacDa: string;
    setMauSacDa: React.Dispatch<React.SetStateAction<string>>;
    longBanTay: string;
    setLongBanTay: React.Dispatch<React.SetStateAction<string>>;
    thop: string;
    setThop: React.Dispatch<React.SetStateAction<string>>;
    kichThuocDau: string;
    setKichThuocDau: React.Dispatch<React.SetStateAction<string>>;
    vanDongCo: string;
    setVanDongCo: React.Dispatch<React.SetStateAction<string>>;
    khoiBatThuongDauCo: string;
    setKhoiBatThuongDauCo: React.Dispatch<React.SetStateAction<string>>;
    viTri2Mat: string;
    setViTri2Mat: React.Dispatch<React.SetStateAction<string>>;
    miMatKetMac: string;
    setMiMatKetMac: React.Dispatch<React.SetStateAction<string>>;
    lacMat: string;
    setLacMat: React.Dispatch<React.SetStateAction<string>>;
    dongTu: string;
    setDongTu: React.Dispatch<React.SetStateAction<string>>;
    taiMangNhi: string;
    setTaiMangNhi: React.Dispatch<React.SetStateAction<string>>;
    dapUngAmThanh: string;
    setDapUngAmThanh: React.Dispatch<React.SetStateAction<string>>;
    khoiSungSauTai: string;
    setKhoiSungSauTai: React.Dispatch<React.SetStateAction<string>>;
    chayMuNuocTai: string;
    setChayMuNuocTai: React.Dispatch<React.SetStateAction<string>>;
    hinhDangMui: string;
    setHinhDangMui: React.Dispatch<React.SetStateAction<string>>;
    chayNuocMui: string;
    setChayNuocMui: React.Dispatch<React.SetStateAction<string>>;
    nghetMui: string;
    setNghetMui: React.Dispatch<React.SetStateAction<string>>;
    hong: string;
    setHong: React.Dispatch<React.SetStateAction<string>>;
    hinhDangMieng: string;
    setHinhDangMieng: React.Dispatch<React.SetStateAction<string>>;
    rangSuaSoSinh: string;
    setRangSuaSoSinh: React.Dispatch<React.SetStateAction<string>>;
    hinhDangLuoi: string;
    setHinhDangLuoi: React.Dispatch<React.SetStateAction<string>>;
    dinhThangLuoi: string;
    setDinhThangLuoi: React.Dispatch<React.SetStateAction<string>>;
    namMieng: string;
    setNamMieng: React.Dispatch<React.SetStateAction<string>>;
    camNhoTutSau: string;
    setCamNhoTutSau: React.Dispatch<React.SetStateAction<string>>;
    vetSauMangBam: string;
    setVetSauMangBam: React.Dispatch<React.SetStateAction<string>>;
    nhipThoKhongDeu: string;
    setNhipThoKhongDeu: React.Dispatch<React.SetStateAction<string>>;
    thoRutLomLongNguc: string;
    setThoRutLomLongNguc: React.Dispatch<React.SetStateAction<string>>;
    tiengThoBatThuong: string;
    setTiengThoBatThuong: React.Dispatch<React.SetStateAction<string>>;
    dhSuyHoHap: string;
    setDhSuyHoHap: React.Dispatch<React.SetStateAction<string>>;
    nghePhoi: string;
    setNghePhoi: React.Dispatch<React.SetStateAction<string>>;
    viTriMomTim: string;
    setViTriMomTim: React.Dispatch<React.SetStateAction<string>>;
    machNgoaiVi: string;
    setMachNgoaiVi: React.Dispatch<React.SetStateAction<string>>;
    ngheTim: string;
    setNgheTim: React.Dispatch<React.SetStateAction<string>>;
    hinhDangBungRon: string;
    setHinhDangBungRon: React.Dispatch<React.SetStateAction<string>>;
    ganLachTo: string;
    setGanLachTo: React.Dispatch<React.SetStateAction<string>>;
    khoiBatThuongBung: string;
    setKhoiBatThuongBung: React.Dispatch<React.SetStateAction<string>>;
    loHauMon: string;
    setLoHauMon: React.Dispatch<React.SetStateAction<string>>;
    cqSinhDucNgoai: string;
    setCqSinhDucNgoai: React.Dispatch<React.SetStateAction<string>>;
    vanDongKhongDoiXung: string;
    setVanDongKhongDoiXung: React.Dispatch<React.SetStateAction<string>>;
    phanXaBu: string;
    setPhanXaBu: React.Dispatch<React.SetStateAction<string>>;
    phanXaNam: string;
    setPhanXaNam: React.Dispatch<React.SetStateAction<string>>;
    phanXaMoro: string;
    setphanXaMoro: React.Dispatch<React.SetStateAction<string>>;
    truongLucCo: string;
    setTruongLucCo: React.Dispatch<React.SetStateAction<string>>;
    khopHang: string;
    setKhopHang: React.Dispatch<React.SetStateAction<string>>;
    phanXaCo: string;
    setPhanXaCo: React.Dispatch<React.SetStateAction<string>>;
    kiemTraLungCotSong: string;
    setKiemTraLungCotSong: React.Dispatch<React.SetStateAction<string>>;
    khamTuChiKhop: string;
    setKhamTuChiKhop: React.Dispatch<React.SetStateAction<string>>;
    quanSatDangDi: string;
    setQuanSatDangDi: React.Dispatch<React.SetStateAction<string>>;

    // 6. Conclusion
    fitnessClass: string;
    setFitnessClass: React.Dispatch<React.SetStateAction<string>>;
    diagnosis: string;
    setDiagnosis: React.Dispatch<React.SetStateAction<string>>;
    cacVanDeLuuY: string;
    setCacVanDeLuuY: React.Dispatch<React.SetStateAction<string>>;
    cacBenhTatNeuCo: string;
    setCacBenhTatNeuCo: React.Dispatch<React.SetStateAction<string>>;
    benhDangDieuTri: string;
    setBenhDangDieuTri: React.Dispatch<React.SetStateAction<string>>;
    tsbtDangDieuTriBenh: string;
    setTsbtDangDieuTriBenh: React.Dispatch<React.SetStateAction<string>>;
    ketLuanLoaiSucKhoe: string;
    setKetLuanLoaiSucKhoe: React.Dispatch<React.SetStateAction<string>>;
    conclusionDoctorId: string;
    setConclusionDoctorId: React.Dispatch<React.SetStateAction<string>>;
    quanLyBenh: string;
    setQuanLyBenh: React.Dispatch<React.SetStateAction<string>>;
    theoDoiTai: string;
    setTheoDoiTai: React.Dispatch<React.SetStateAction<string>>;
    chuyenTuyen: string;
    setChuyenTuyen: React.Dispatch<React.SetStateAction<string>>;

    errors: Record<string, string>;
    setErrors: React.Dispatch<React.SetStateAction<Record<string, string>>>;

    // Workflow optimizations
    isLocked: boolean;
    setIsLocked: React.Dispatch<React.SetStateAction<boolean>>;
    isSyncingParaclinical: boolean;
    handleSyncParaclinical: () => Promise<void>;
    handleAutofillTab: (tabKey: string) => void;
}

export const DynamicFormContext = createContext<DynamicFormContextType | undefined>(undefined);

export const useDynamicFormContext = () => {
    const context = useContext(DynamicFormContext);
    if (!context) {
        throw new Error('useDynamicFormContext must be used within a DynamicFormContextProvider');
    }
    return context;
};
