ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_dob DATE;
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_gender VARCHAR(10);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_identity_card VARCHAR(20);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_email VARCHAR(100);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_address TEXT;

ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_hmmodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_tramodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_inmodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_nmmodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_tmvmodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_dsmmodule VARCHAR(1);
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS su_hms_itsmodule VARCHAR(1);

ALTER TABLE IF EXISTS hms_exm_contract ADD COLUMN hec_status character varying(1);
