<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Vimes.Agent.Printing</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vimes.Agent.Contracts\Vimes.Agent.Contracts.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
