import React, { useEffect, useState } from 'react';
import { templateStudioService } from '../../../services/templateStudioService';
import { MappingDraftForm } from './MappingDraftForm';

export const MappingStudioPanel: React.FC = () => {
  const [items, setItems] = useState<any[]>([]); const [moduleCode, setModuleCode] = useState(''); const [contractCode, setContractCode] = useState(''); const [status, setStatus] = useState(''); const [rules, setRules] = useState('[]'); const [source, setSource] = useState('{}'); const [preview, setPreview] = useState(''); const [error, setError] = useState(''); const [selectedId, setSelectedId] = useState<number>();
  const load = async () => { try { setError(''); setItems(await templateStudioService.mappings({ moduleCode: moduleCode || undefined, contractCode: contractCode || undefined, status: status || undefined })); } catch (e) { setError(e instanceof Error ? e.message : 'Không tải được mapping'); } };
  useEffect(() => { load(); }, [moduleCode, contractCode, status]);
  const runPreview = async () => { try { setError(''); setPreview(JSON.stringify(await templateStudioService.previewMapping({ mappings: JSON.parse(rules), sourceData: JSON.parse(source) }), null, 2)); } catch (e) { setError(e instanceof Error ? e.message : 'Preview mapping thất bại'); } };
  const selectMapping = (item: any) => { setSelectedId(item.id); setRules(JSON.stringify(item.mappings || [], null, 2)); };
  const createVersion = async () => { const item = items.find(value => value.id === selectedId); if (!item) return; try { await templateStudioService.createMappingVersion(item.code, JSON.parse(rules)); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không tạo được version mapping'); } };
  const transition = async (action: 'publish' | 'retire') => { const item = items.find(value => value.id === selectedId); if (!item) return; try { if (action === 'publish') await templateStudioService.publishMapping(item.code); else await templateStudioService.retireMapping(item.code); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không chuyển trạng thái mapping'); } };
  return <div className="space-y-4 rounded-xl border bg-white p-4 dark:bg-slate-900">
    <div className="flex flex-wrap gap-2"><input value={moduleCode} onChange={e => setModuleCode(e.target.value)} placeholder="Module" className="rounded border px-2 py-1 text-sm" /><input value={contractCode} onChange={e => setContractCode(e.target.value)} placeholder="Contract" className="rounded border px-2 py-1 text-sm" /><select value={status} onChange={e => setStatus(e.target.value)} className="rounded border px-2 py-1 text-sm"><option value="">Tất cả trạng thái</option><option>DRAFT</option><option>PUBLISHED</option><option>RETIRED</option></select><button type="button" onClick={load} className="rounded bg-blue-600 px-3 py-1 text-sm text-white">Làm mới</button></div>
    <MappingDraftForm rules={rules} onCreated={load} onError={setError} />{selectedId && <div className="flex gap-2"><button type="button" onClick={createVersion} disabled={items.find(item => item.id === selectedId)?.status === 'DRAFT'} className="rounded border border-amber-600 px-3 py-1 text-sm text-amber-700 disabled:opacity-50">Tạo version mới</button><button type="button" onClick={() => transition('publish')} disabled={items.find(item => item.id === selectedId)?.status !== 'DRAFT'} className="rounded bg-blue-600 px-3 py-1 text-sm text-white disabled:opacity-50">Publish</button><button type="button" onClick={() => transition('retire')} disabled={items.find(item => item.id === selectedId)?.status !== 'PUBLISHED'} className="rounded border border-red-600 px-3 py-1 text-sm text-red-700 disabled:opacity-50">Retire</button></div>}
    <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="mb-2 font-semibold">Mapping hiện có</h3><div className="max-h-48 overflow-auto divide-y rounded border">{items.map(item => <button type="button" key={item.id} onClick={() => selectMapping(item)} className={`block w-full p-2 text-left text-sm ${selectedId === item.id ? 'bg-blue-50' : 'hover:bg-slate-50'}`}><b>{item.code}</b> · v{item.version}<span className="ml-2 text-xs text-slate-500">{item.module_code} → {item.contract_code} · {item.status}</span></button>)}{!items.length && <div className="p-3 text-xs text-slate-500">Chưa có mapping phù hợp.</div>}</div></div>
      <div><h3 className="mb-2 font-semibold">Preview mapping</h3><textarea value={rules} onChange={e => setRules(e.target.value)} className="mb-2 h-24 w-full rounded border bg-slate-950 p-2 font-mono text-xs text-white" placeholder="Mapping rules JSON" /><textarea value={source} onChange={e => setSource(e.target.value)} className="mb-2 h-24 w-full rounded border bg-slate-950 p-2 font-mono text-xs text-white" placeholder="Source data JSON" /><button type="button" onClick={runPreview} className="rounded bg-emerald-600 px-3 py-1 text-sm text-white">Chạy preview</button>{preview && <pre className="mt-2 max-h-40 overflow-auto rounded bg-slate-950 p-2 text-xs text-emerald-300">{preview}</pre>}</div></div>
    {error && <div className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</div>}
  </div>;
};
