import { query } from '../config/database';
import { PdfSignatureRect } from './signature.types';

export class PlaceholderRepository {
    async list(templateVersionId: number) { const result = await query('SELECT * FROM hms_document_signature_placeholder WHERE template_version_id=$1 AND status<>\'RETIRED\' ORDER BY signing_order, code', [templateVersionId]); return result.rows; }
    async create(templateVersionId: number, input: PdfSignatureRect & { templateId?: number; code: string; fieldName?: string; signerRole: string; signingOrder?: number; required?: boolean; appearanceProfileId?: string }, actor: string) {
        const overlap = await query(`SELECT 1 FROM hms_document_signature_placeholder WHERE template_version_id=$1 AND status<>'RETIRED' AND page_index=$2 AND x1_pt < $5 AND x2_pt > $3 AND y1_pt < $6 AND y2_pt > $4 LIMIT 1`, [templateVersionId, input.pageIndex, input.x1Pt, input.y1Pt, input.x2Pt, input.y2Pt]);
        if (overlap.rows[0]) throw Object.assign(new Error('Placeholder overlaps an existing signature region'), { status: 409, code: 'PLACEHOLDER_OVERLAP' });
        const result = await query(`INSERT INTO hms_document_signature_placeholder (template_id, template_version_id, code, field_name, signer_role, signing_order, page_index, x1_pt, y1_pt, x2_pt, y2_pt, page_width_pt, page_height_pt, page_rotation, crop_box, normalized_rect, required, appearance_profile_id, created_by) SELECT COALESCE($1, (SELECT template_id FROM hms_document_template_version WHERE id=$2)),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16::jsonb,$17,$18,$19 WHERE EXISTS (SELECT 1 FROM hms_document_template_version WHERE id=$2 AND status='DRAFT') RETURNING *`, [input.templateId || null, templateVersionId, input.code, input.fieldName || null, input.signerRole, input.signingOrder || 1, input.pageIndex, input.x1Pt, input.y1Pt, input.x2Pt, input.y2Pt, input.pageWidthPt, input.pageHeightPt, input.pageRotation, JSON.stringify([0, 0, input.pageWidthPt, input.pageHeightPt]), JSON.stringify({ x: input.x1Pt / input.pageWidthPt, y: input.y1Pt / input.pageHeightPt, width: (input.x2Pt - input.x1Pt) / input.pageWidthPt, height: (input.y2Pt - input.y1Pt) / input.pageHeightPt }), input.required !== false, input.appearanceProfileId || null, actor]);
        if (!result.rows[0]) throw Object.assign(new Error('Placeholder can only be created on a draft template version'), { status: 409, code: 'PLACEHOLDER_VERSION_NOT_DRAFT' }); return result.rows[0];
    }
    async update(id: number, input: Partial<PdfSignatureRect> & { code?: string; fieldName?: string; signerRole?: string; signingOrder?: number; required?: boolean; appearanceProfileId?: string }) {
        if (input.pageIndex !== undefined && input.x1Pt !== undefined && input.y1Pt !== undefined && input.x2Pt !== undefined && input.y2Pt !== undefined) {
            const current = await query('SELECT template_version_id FROM hms_document_signature_placeholder WHERE id=$1', [id]);
            if (current.rows[0]) { const overlap = await query(`SELECT 1 FROM hms_document_signature_placeholder WHERE template_version_id=$1 AND id<>$2 AND status<>'RETIRED' AND page_index=$3 AND x1_pt < $6 AND x2_pt > $4 AND y1_pt < $7 AND y2_pt > $5 LIMIT 1`, [current.rows[0].template_version_id, id, input.pageIndex, input.x1Pt, input.y1Pt, input.x2Pt, input.y2Pt]); if (overlap.rows[0]) throw Object.assign(new Error('Placeholder overlaps an existing signature region'), { status: 409, code: 'PLACEHOLDER_OVERLAP' }); }
        }
        const result = await query(`UPDATE hms_document_signature_placeholder p SET code=COALESCE($2,code), field_name=COALESCE($3,field_name), signer_role=COALESCE($4,signer_role), signing_order=COALESCE($5,signing_order), page_index=COALESCE($6,page_index), x1_pt=COALESCE($7,x1_pt), y1_pt=COALESCE($8,y1_pt), x2_pt=COALESCE($9,x2_pt), y2_pt=COALESCE($10,y2_pt), page_width_pt=COALESCE($11,page_width_pt), page_height_pt=COALESCE($12,page_height_pt), page_rotation=COALESCE($13,page_rotation), crop_box=CASE WHEN $11 IS NOT NULL OR $12 IS NOT NULL THEN jsonb_build_array(0,0,COALESCE($11,page_width_pt),COALESCE($12,page_height_pt)) ELSE crop_box END, normalized_rect=CASE WHEN $7 IS NOT NULL OR $8 IS NOT NULL OR $9 IS NOT NULL OR $10 IS NOT NULL OR $11 IS NOT NULL OR $12 IS NOT NULL THEN jsonb_build_object('x',COALESCE($7,x1_pt)/COALESCE($11,page_width_pt),'y',COALESCE($8,y1_pt)/COALESCE($12,page_height_pt),'width',(COALESCE($9,x2_pt)-COALESCE($7,x1_pt))/COALESCE($11,page_width_pt),'height',(COALESCE($10,y2_pt)-COALESCE($8,y1_pt))/COALESCE($12,page_height_pt)) ELSE normalized_rect END, required=COALESCE($14,required), appearance_profile_id=COALESCE($15,appearance_profile_id), updated_at=NOW() WHERE p.id=$1 AND EXISTS (SELECT 1 FROM hms_document_template_version v WHERE v.id=p.template_version_id AND v.status='DRAFT') RETURNING p.*`, [id, input.code || null, input.fieldName || null, input.signerRole || null, input.signingOrder || null, input.pageIndex ?? null, input.x1Pt ?? null, input.y1Pt ?? null, input.x2Pt ?? null, input.y2Pt ?? null, input.pageWidthPt ?? null, input.pageHeightPt ?? null, input.pageRotation ?? null, input.required ?? null, input.appearanceProfileId || null]);
        if (!result.rows[0]) throw Object.assign(new Error('Placeholder not found or version is not draft'), { status: 409, code: 'PLACEHOLDER_NOT_EDITABLE' }); return result.rows[0];
    }
    async retire(id: number) { const result = await query(`UPDATE hms_document_signature_placeholder p SET status='RETIRED', updated_at=NOW() WHERE p.id=$1 AND EXISTS (SELECT 1 FROM hms_document_template_version v WHERE v.id=p.template_version_id AND v.status='DRAFT') RETURNING p.*`, [id]); if (!result.rows[0]) throw Object.assign(new Error('Placeholder not found or version is not draft'), { status: 409, code: 'PLACEHOLDER_NOT_EDITABLE' }); return result.rows[0]; }
}
